### PR TITLE
fix: use fs.mkdir to instead of mkpath as it was not maintained

### PR DESCRIPTION
**Pull request by kuitos**
see https://github.com/jrajav/mkpath/issues/6

---
This change is [Reviewable](https://reviewable.io/reviews/rollup/rollup-plugin-url/24)

### CODE REVIEW

**Comment by kuitos** [comment]
more detail scenario https://travis-ci.org/umijs/father/jobs/591324449#L285

@Ashot-KR could you pls donate some time to review it?

**Comment by Ashot-KR** [comment]
@kuitos reviewed already. I will merge it and publish new version later today.

**Comment by Ashot-KR** [comment]
2.2.3 published on npm

**Comment by Ashot-KR** [comment]
@kuitos looks like it broke plugin on node <=8 :bowtie: 
now version 2.2.3 marked as deprecated
version 2.2.4 uses `mkdirp` package for node <=8
version 3.0.0 uses your changes and required node >=10 – please use this version (also it migrated to MIT lisense)

**Comment by kuitos** [comment]
Thanks for your great efforts!
I am wonder what behavior broke the plugin on node <=8 🤔
I had checked the version history of `fs.mkdir` before, it added after v0.1.8, the very early version
see https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback

**Comment by Ashot-KR** [comment]
@kuitos It was surprise for me too.
Problem was that `recursive` option for `fs.mkdir` was added in node 10
in node 8 and earlier second parameter was `mode` https://nodejs.org/docs/latest-v8.x/api/fs.html#fs_fs_mkdir_path_mode_callback

**Pull request merged**
