### PR TITLE
docs: add moving notice

### PR DESCRIPTION
**Pull request by pnevares**
Starting the migration to rollup/plugins! 🎉

### CODE REVIEW

**Comment by Ashot-KR** [comment]
Good start point, but i've lost my maintainer role on repo 😕 
@Swatinem can you add me again? I was removed because i didn’t have two-factor authentication, i fixed that

**Comment by Swatinem** [comment]
@Ashot-KR looks like I’m not an owner anymore either (though it looks like I can merge). I guess @lukastaegert or anyone of @rollup/core can help here.

**Comment by shellscape** [comment]
I've got you fellas. Give me a few moments to get that setup again. 

@Ashot-KR you've got an invite. @Swatinem you should be good to go.

**Comment by Ashot-KR** [comment]
@shellscape thanks! 🍻

**Comment by Ashot-KR** [comment]
merged
I'll start migration process ASAP (probably next week, but i'll do my best start it in a few days)

**Comment by pnevares** [comment]
@Ashot-KR I've added some commits in a branch on my fork, it's not complete but the biggest part I have left is updating the tests to use `ava`. https://github.com/pnevares/plugins/tree/add/url

I'm no expert on `rollup-plugin-url` though, so I don't mind scrapping it if a contributor would like to own the migration.

**Comment by Ashot-KR** [comment]
@pnevares didn't see you already started it.
So as I'm not expert on AVA though 😄(but i like it).
If you start working on this, you should continue. I'm always here to help.
I think you should open `WIP` PR to rollup/plugins repo so we can communicate about migration there and work together on migration.

**Comment by pnevares** [comment]
Sounds great! I'll open the PR tonight 👍

**Comment by pnevares** [comment]
WIP PR: https://github.com/rollup/plugins/pull/46

**Pull request merged**
